export type PermissionMode = 'read_only' | 'confirm_writes' | 'trusted_writes' | 'danger_zone';
export type PermissionScope =
  | 'focused_rem_only'
  | 'focused_rem_and_descendants'
  | 'selected_rem_only'
  | 'selected_rem_and_descendants'
  | 'approved_document_or_folder'
  | 'workspace_allowed';

export const WRITE_APPROVAL_TIMEOUT_MS = 30000;

export type BridgeToolName =
  | 'ping'
  | 'get_status'
  | 'get_focused_rem'
  | 'get_rem'
  | 'get_rem_tree'
  | 'get_rem_rich'
  | 'debug_get_raw_rich_text'
  | 'get_current_selection'
  | 'get_children'
  | 'get_rem_breadcrumbs'
  | 'search_rems'
  | 'get_document_or_folder_tree'
  | 'create_rem'
  | 'append_to_rem'
  | 'create_document'
  | 'create_folder'
  | 'update_rem'
  | 'move_rem'
  | 'reorder_children'
  | 'create_rem_tree'
  | 'update_rem_rich'
  | 'set_rem_heading_level'
  | 'set_rem_text_color'
  | 'set_rem_highlight_color'
  | 'set_text_span_color'
  | 'set_text_span_highlight'
  | 'set_rem_type'
  | 'set_hide_bullet'
  | 'clear_rem_formatting'
  | 'create_styled_rem_tree'
  | 'apply_remnote_command'
  | 'apply_structured_note_batch'
  | 'create_polished_note_tree'
  | 'create_or_replace_note_from_markdown'
  | 'apply_style_plan'
  | 'verify_note_design'
  | 'create_basic_flashcard'
  | 'create_concept_card'
  | 'create_descriptor_card'
  | 'create_cloze_card'
  | 'create_multiple_choice_card'
  | 'create_list_answer_card'
  | 'replace_rem'
  | 'delete_rem_by_id';

export type ReadOnlyBridgeToolName =
  | 'get_focused_rem'
  | 'get_rem'
  | 'get_rem_tree'
  | 'get_rem_rich'
  | 'debug_get_raw_rich_text'
  | 'get_current_selection'
  | 'get_children'
  | 'get_rem_breadcrumbs'
  | 'search_rems'
  | 'get_document_or_folder_tree'
  | 'verify_note_design';
export type SafeWriteBridgeToolName =
  | 'create_rem'
  | 'append_to_rem'
  | 'create_document'
  | 'create_folder'
  | 'update_rem'
  | 'move_rem'
  | 'reorder_children'
  | 'create_rem_tree'
  | 'update_rem_rich'
  | 'set_rem_heading_level'
  | 'set_rem_text_color'
  | 'set_rem_highlight_color'
  | 'set_text_span_color'
  | 'set_text_span_highlight'
  | 'set_rem_type'
  | 'set_hide_bullet'
  | 'clear_rem_formatting'
  | 'create_styled_rem_tree'
  | 'apply_remnote_command'
  | 'apply_structured_note_batch'
  | 'create_polished_note_tree'
  | 'create_or_replace_note_from_markdown'
  | 'apply_style_plan'
  | 'create_basic_flashcard'
  | 'create_concept_card'
  | 'create_descriptor_card'
  | 'create_cloze_card'
  | 'create_multiple_choice_card'
  | 'create_list_answer_card';
export type DangerousBridgeToolName =
  | 'replace_rem'
  | 'delete_rem_by_id';

export type BridgeErrorCode =
  | 'NO_FOCUSED_REM'
  | 'REM_NOT_FOUND'
  | 'PARENT_NOT_FOUND'
  | 'PLUGIN_NOT_CONNECTED'
  | 'PLUGIN_NOT_PAIRED'
  | 'NO_PAIRED_PLUGIN_SESSION'
  | 'HOSTED_SESSION_MISSING'
  | 'DEVICE_CONFLICT'
  | 'PLUGIN_SESSION_EXPIRED'
  | 'PLUGIN_SESSION_REVOKED'
  | 'NO_ACTIVE_DEVICE'
  | 'INVALID_ARGS'
  | 'PERMISSION_DENIED'
  | 'INSUFFICIENT_SCOPE'
  | 'TRUSTED_WRITE_REQUIRED'
  | 'OUT_OF_SCOPE'
  | 'APPROVAL_REJECTED'
  | 'APPROVAL_TIMEOUT'
  | 'SDK_UNSUPPORTED'
  | 'SDK_ERROR'
  | 'TIMEOUT'
  | 'CLIENT_DISCONNECTED'
  | 'RETRYABLE_UNKNOWN_WRITE_STATUS'
  | 'RETRYABLE_UNKNOWN_DELETE_STATUS'
  | 'REQUEST_CANCELLED'
  | 'UNKNOWN_TOOL'
  | 'APPROVAL_PENDING'
  | 'OPERATION_PENDING'
  | 'PARTIAL_FAILURE'
  | 'ROLLBACK_FAILED'
  | 'SOURCE_FIDELITY_FAILED'
  | 'TOOL_UNSUPPORTED'
  | 'TOOL_HIDDEN_BY_PROFILE'
  | 'INTERNAL_ERROR';

export type ApprovalResolution =
  | 'APPROVED'
  | 'APPROVAL_REJECTED'
  | 'APPROVAL_TIMEOUT'
  | 'APPROVAL_PENDING'
  | 'REQUEST_CANCELLED';
export type ApprovalRiskLevel = 'safe_write' | 'destructive';
export type BridgeLifecyclePhase =
  | 'received'
  | 'validated'
  | 'waiting_for_chatgpt_permission'
  | 'waiting_for_remnote_approval'
  | 'waiting_for_approval'
  | 'approval_approved'
  | 'approval_rejected'
  | 'approval_timeout'
  | 'executing'
  | 'completed'
  | 'failed'
  | 'partial_failure'
  | 'rollback_started'
  | 'rollback_completed'
  | 'rollback_failed'
  | 'cancelled'
  | 'timeout';

export interface BridgeLifecycleEvent {
  phase: BridgeLifecyclePhase;
  at: string;
  message?: string;
}

